// <auto-generated />
namespace Version_4.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ContextoBD3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ContextoBD3));
        
        string IMigrationMetadata.Id
        {
            get { return "202010111528156_ContextoBD3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
