// <auto-generated />
namespace CETAF_MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ContextoDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ContextoDB));
        
        string IMigrationMetadata.Id
        {
            get { return "202010050027296_ContextoDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
